language: python

python:
  - "2.7"

services: postgresql

env:
  - DJANGO_VERSION=1.5

install:
  - "pip install -r requirements.txt"

before_script:
  - psql -c "CREATE DATABASE ly;" -U postgres
  - touch twly-voter-guide/ly/local_settings.py

script: coverage run manage.py test --settings=ly.test
