language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=1.5 DB=postgres

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors
  - pip install -r requirements.txt --use-mirrors

script:
  - python manage.py test
