language: python

python:
  - "2.7"

services:
  - elasticsearch

addons:
  postgresql: "9.3"

env:
  - DJANGO_VERSION=1.8

install:
  - "pip install -r requirements.txt"

before_script:
  - psql -c "CREATE DATABASE ly;" -U postgres
  - touch ly/local_settings.py

script: coverage run manage.py test --settings=ly.test
