language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO_VERSION=1.5

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors
  - pip install -r requirements.txt --use-mirrors

script:
  - coverage run manage.py test --settings=ly.test
